from igramscraper.two_step_verification.two_step_verification_abstract_class import TwoStepVerificationAbstractClass
from igramscraper.two_step_verification.console_verification import ConsoleVerification

__all__ = ["TwoStepVerificationAbstractClass", "ConsoleVerification"]
